# Generated by Django 4.2 on 2023-06-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_food_calories_alter_food_carbohydrate_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staredfood',
            unique_together={('food', 'user')},
        ),
    ]
